# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  deno: ksylvest/deno@1.0.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  run-specs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - deno/install
      - run:
          name: Run specs
          command: deno task test:all

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  run-specs:
    jobs:
      - run-specs